### ISSUE TITLE
Create initial API scaffolding

### ISSUE THREAD

**Issue by davidhjones** [urbanengine/UrbanEngineApi#1]
Create the initial scaffolding for the Asp Net Core API. This should expose one controller-based API, with a single GET endpoint which returns the object sent in the body --- no persistence.

Items which should be included in the scaffolding:

- Dependency Injection
  - Autofac (https://autofaccn.readthedocs.io/en/latest/integration/aspnetcore.html). Using Autofac's module setup
- Logging
  - Serilog (We use the Sink Seq at work, but it doesn't seem to have a paid tier -- we could always just go full Azure and use the Application Insights Sink).
- Entity Validation
  - FluentValidation is a really good one
- Middlewares
  - Auth0 (for API authentication)
- API Language
  - ODATA. Can leverage AspNetCore.OData nuget. This means we will need to implement ODataControllers instead of ApiControllers (OdataControllers inherit from APIControllers but add another layer on top).

**Comment by tylerbhughes** [comment]
@scottluskcis I could use your help on this task. I've been working on the solution-setup branch and have gotten most of the dependency injection set up. However, my current impediment when I run the project my `DbRepository` class expects a DbContext to be passed into it and I'm not sure how to get around that with Autofac. If we need to switch from Autofac to just the .NET Core DI implementation I'm fine with that but I'd really like to get past this issue.

Beyond that Serilog with Application Insights still needs to be set up. Should we have a logger that's a singleton? I would think that's something that we would never need more than one instance of it. 

 I can set up the Auth0 stuff. 

OData I'm still not fully familiar with so it probably wouldn't hurt for us to chat about that and how it would affect the way the code will be built. 

Thoughs?

**Comment by scottluskcis** [comment]
Thanks @tylerbhughes I'll start taking a look at this. I can provide you with some examples of using .NET Core DI and EF Core DbContext with that. I've got examples of Serilog and App Insights as well both using that approach for DI. AutoFac is great but they are doing so much with DI on Core side its easier to follow examples from the docs 

here is a link to DI, I'm sure you've seen it 
[Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1)

here is link to context 
[EntityFrameworkServiceCollectionExtensions.AddDbContext Method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.entityframeworkservicecollectionextensions.adddbcontext?view=efcore-2.1)

I'll let you know what else I see as I dig into this
